; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
src_dir = src
data_dir = littlefs_data

[env:unihiker_k10_spectrum]
platform = https://github.com/DFRobot/platform-unihiker.git
framework = espidf
board = unihiker_k10
monitor_speed = 115200
monitor_filters = direct
extra_scripts = extra_script.py
board_build.partitions = src/partitions.csv
build_flags = -Wno-error
build_unflags = -Werror
board_build.littlefs_dir = littlefs_data
board_build.filesystem = littlefs
